/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package learn.kotlin.unit.test

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        println("testing")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
